env:
  node: true
  mocha: true
  es6: true
plugins: ["mocha", "prettier"]
extends: ["eslint:recommended", "google", "prettier"]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  "no-invalid-this": ["off"],
  "max-len": [2, {"code": 200, "tabWidth": 2, "ignoreUrls": true}],
  "prettier/prettier": ["error"],
  "indent": [2, 2, {"SwitchCase": 1}],
  "require-jsdoc": ["off"],
  "require-atomic-updates": ["off"]
}
